### ISSUE TITLE
TableView reuse problem

### ISSUE THREAD

**Issue by xinzhengzhang** [ukiyoevega/Votes#1]
https://github.com/ukiyoevega/Votes/blob/master/Votes/Controller/VoteDetailViewController.swift#L404

https://github.com/ukiyoevega/Votes/blob/master/Votes/Controller/VoteDetailViewController.swift#L103

```
- (nullable __kindof UITableViewCell *)dequeueReusableCellWithIdentifier:(NSString *)identifier;  // Used by the delegate to acquire an already allocated cell, in lieu of allocating a new one.
```

Add your subviews into cell which enqueued into the reusable queue.
What you write is just reuse the `UITableViewCell`. And I found that you have registered the `voteCell` but never used it.

**Comment by ukiyoevega** [comment]
Thanks for pointing out the problems.
I've cut out the extra line and for the first one, I get a reusable UITableViewCell object located by its identifier and add subviews into it, that's correct.

**Comment by xinzhengzhang** [comment]
No, it will cause the tableview create and remake it's subviews and constraints every time when it scrolled to be visible. And it resulting in a huge waste of performance. 
The correct way is register a custom cell like `voteCell` and dequeue it from tableview cell delegate. Then layout (no need for using autolayout ) and reuse it.

**Comment by ukiyoevega** [comment]
I see...I do it wrong by keeping the "addSubviews" method repeating for a default UITableViewCell dequeue from the reuse queue. 
Thank you.
